# Generated by Django 5.0.1 on 2024-01-18 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_range_min", models.IntegerField(default=18)),
                ("age_range_max", models.IntegerField(default=50)),
                ("distance_range", models.IntegerField(default=50)),
                ("gender_preference", models.CharField(default="All", max_length=50)),
                ("interests", models.TextField(blank=True, default="")),
                ("profile_visibility", models.BooleanField(default=True)),
                ("location_sharing", models.BooleanField(default=True)),
                ("block_list", models.TextField(blank=True, default="")),
                ("new_match_notifications", models.BooleanField(default=True)),
                ("message_notifications", models.BooleanField(default=True)),
                ("app_updates_notifications", models.BooleanField(default=True)),
                ("email_preferences", models.CharField(default="All", max_length=50)),
                (
                    "language_preference",
                    models.CharField(default="English", max_length=50),
                ),
                ("account_deactivation", models.BooleanField(default=False)),
                ("theme", models.CharField(default="Light", max_length=50)),
                (
                    "accessibility_settings",
                    models.CharField(default="Default", max_length=200),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
