# Generated by Django 5.0.1 on 2024-02-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_url",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
    ]
