# Generated by Django 5.0.1 on 2024-02-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_image_image_url_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
