# Generated by Django 5.0.1 on 2024-01-27 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("users", "0005_remove_userprofile_additional_images_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="is_read",
            new_name="read",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="date_created",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="content",
        ),
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.image",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("favorite", "Favorite"),
                    ("message", "Message"),
                    ("game_request", "Game Request"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["-timestamp"], name="notificatio_timesta_3d6780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read"], name="notificatio_recipie_6e3964_idx"
            ),
        ),
    ]
